# This is the official, perfected, and final instruction manual for our GitHub Actions factory
name: One-Click Publisher Build Worker

on:
  workflow_dispatch: # This allows us to run it manually

jobs:
  build:
    runs-on: ubuntu-latest # The factory will use a clean, powerful Linux machine

    # Granting the factory permission to talk back to our city's database
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout the blueprints
        uses: actions/checkout@v3 # Step 1: Get the worker's own code

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Step 2: Install the main power tool
        with:
          node-version: '16'

      - name: Install factory parts
        run: npm install # Step 3: Gather all the tools from package.json

      - name: Authenticate with Google Cloud
        # This is the NEW, UPGRADED, and CORRECT version of the key
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Unleash the Worker
        run: npm start # Step 4: Run our build_worker_v2.js script and bring the dream to life

