# This is the official instruction manual for our GitHub Actions factory
name: One-Click Publisher Build Worker

# This tells the factory to wake up ONLY when we send it a special signal from our Firebase Function
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # The factory will use a clean, powerful Linux machine

    steps:
      - name: Checkout the blueprints
        uses: actions/checkout@v3 # Step 1: Get the worker's own code

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Step 2: Install the main power tool
        with:
          node-version: '16'

      - name: Install factory parts
        run: npm install # Step 3: Gather all the necessary tools from package.json

      - name: Authenticate with Google Cloud
        # This is the magic key that lets our factory talk back to our city's database
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Unleash the Worker
        run: npm start # Step 4: Run our build_worker_v2.js script and bring the dream to life
        
